# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'security.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys

import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from PyQt5 import QtCore, QtGui, QtWidgets

import icons


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(873, 528)
        # MainWindow.setWindowFlags(
        #     (MainWindow.windowFlags() & ~Qt.WindowMaximizeButtonHint)
        #     | Qt.CustomizeWindowHint
        # )
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/Icons/Images/voice-recognition.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.permissionsWidget = QtWidgets.QWidget(self.widget_2)
        self.permissionsWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.permissionsWidget.setObjectName("permissionsWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.permissionsWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.permissionsWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.PermissionsLabel = QtWidgets.QLabel(self.splitter)
        self.PermissionsLabel.setMaximumSize(QtCore.QSize(80, 30))
        self.PermissionsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.PermissionsLabel.setObjectName("PermissionsLabel")
        self.verticalLayout_2.addWidget(self.splitter)
        self.name01Check = QtWidgets.QCheckBox(self.permissionsWidget)
        self.name01Check.setObjectName("name01Check")
        self.verticalLayout_2.addWidget(self.name01Check)
        self.name02Check = QtWidgets.QCheckBox(self.permissionsWidget)
        self.name02Check.setObjectName("name02Check")
        self.verticalLayout_2.addWidget(self.name02Check)
        self.name03Check = QtWidgets.QCheckBox(self.permissionsWidget)
        self.name03Check.setObjectName("name03Check")
        self.verticalLayout_2.addWidget(self.name03Check)
        self.name04Check = QtWidgets.QCheckBox(self.permissionsWidget)
        self.name04Check.setObjectName("name04Check")
        self.verticalLayout_2.addWidget(self.name04Check)
        self.name05Check = QtWidgets.QCheckBox(self.permissionsWidget)
        self.name05Check.setObjectName("name05Check")
        self.verticalLayout_2.addWidget(self.name05Check)
        self.name06Check = QtWidgets.QCheckBox(self.permissionsWidget)
        self.name06Check.setObjectName("name06Check")
        self.verticalLayout_2.addWidget(self.name06Check)
        self.name07Check = QtWidgets.QCheckBox(self.permissionsWidget)
        self.name07Check.setObjectName("name07Check")
        self.verticalLayout_2.addWidget(self.name07Check)
        self.name08Check = QtWidgets.QCheckBox(self.permissionsWidget)
        self.name08Check.setObjectName("name08Check")
        self.verticalLayout_2.addWidget(self.name08Check)
        self.verticalLayout_4.addWidget(self.permissionsWidget)
        spacerItem = QtWidgets.QSpacerItem(
            20, 220, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_4.addItem(spacerItem)
        self.gridLayout.addWidget(self.widget_2, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.spectrogramFrame = QtWidgets.QFrame(self.groupBox)
        self.spectrogramFrame.setAutoFillBackground(False)
        self.spectrogramFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.spectrogramFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.spectrogramFrame.setObjectName("spectrogramFrame")

        self.horizontalLayout01 = QtWidgets.QVBoxLayout(self.spectrogramFrame)
        self.horizontalLayout01.setObjectName("HorizCanv01")
        self.spectroFigure = plt.figure()
        self.spectroCanvas = FigureCanvas(self.spectroFigure)
        self.horizontalLayout01.addWidget(self.spectroCanvas)

        self.verticalLayout.addWidget(self.spectrogramFrame)
        self.probabilitySplitter = QtWidgets.QSplitter(self.groupBox)
        self.probabilitySplitter.setOrientation(QtCore.Qt.Horizontal)
        self.probabilitySplitter.setObjectName("probabilitySplitter")
        self.probabilityLabel = QtWidgets.QLabel(self.probabilitySplitter)
        self.probabilityLabel.setMaximumSize(QtCore.QSize(100, 30))
        self.probabilityLabel.setObjectName("probabilityLabel")
        self.probabilityPercentage = QtWidgets.QLabel(self.probabilitySplitter)
        self.probabilityPercentage.setMaximumSize(QtCore.QSize(100, 30))
        self.probabilityPercentage.setObjectName("probabilityPercentage")
        self.verticalLayout.addWidget(self.probabilitySplitter)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter_2 = QtWidgets.QSplitter(self.widget_4)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.recordWidget = QtWidgets.QWidget(self.splitter_2)
        self.recordWidget.setObjectName("recordWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.recordWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_3.addItem(spacerItem1)
        self.recordButton = QtWidgets.QPushButton(self.recordWidget)
        self.recordButton.setStyleSheet("QPushButton { background-color: transparent }")
        self.recordButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(":/Icons/Images/voice-recording.png"),
            QtGui.QIcon.Normal,
            QtGui.QIcon.Off,
        )
        self.recordButton.setIcon(icon1)
        self.recordButton.setIconSize(QtCore.QSize(64, 64))
        self.recordButton.setObjectName("recordButton")
        self.horizontalLayout_3.addWidget(self.recordButton)
        spacerItem2 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_3.addItem(spacerItem2)
        self.widget_3 = QtWidgets.QWidget(self.splitter_2)
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(
            143, 61, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem3)
        self.lockUnlockIcon = QtWidgets.QLabel(self.widget_3)
        self.lockUnlockIcon.setMinimumSize(QtCore.QSize(50, 50))
        self.lockUnlockIcon.setMaximumSize(QtCore.QSize(50, 50))
        self.lockUnlockIcon.setText("")
        self.lockUnlockIcon.setPixmap(QtGui.QPixmap(":/Icons/Images/locked.png"))
        self.lockUnlockIcon.setScaledContents(True)
        self.lockUnlockIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.lockUnlockIcon.setObjectName("lockUnlockIcon")
        self.horizontalLayout.addWidget(self.lockUnlockIcon)
        self.accessLabel = QtWidgets.QLabel(self.widget_3)
        self.accessLabel.setMaximumSize(QtCore.QSize(16777215, 100))
        self.accessLabel.setObjectName("accessLabel")
        self.horizontalLayout.addWidget(self.accessLabel)
        spacerItem4 = QtWidgets.QSpacerItem(
            38, 85, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem4)
        self.horizontalLayout_2.addWidget(self.splitter_2)
        self.verticalLayout_5.addWidget(self.widget_4)
        self.gridLayout.addWidget(self.widget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 873, 21))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Security System"))
        self.PermissionsLabel.setText(_translate("MainWindow", "Permissions"))
        self.name01Check.setText(_translate("MainWindow", "1st person"))
        self.name02Check.setText(_translate("MainWindow", "2nd person"))
        self.name03Check.setText(_translate("MainWindow", "3th person"))
        self.name04Check.setText(_translate("MainWindow", "4th person"))
        self.name05Check.setText(_translate("MainWindow", "5th person"))
        self.name06Check.setText(_translate("MainWindow", "6th person"))
        self.name07Check.setText(_translate("MainWindow", "7th person"))
        self.name08Check.setText(_translate("MainWindow", "8th person"))
        self.groupBox.setTitle(_translate("MainWindow", "Spectrogram"))
        self.probabilityLabel.setText(_translate("MainWindow", "Probability:"))
        self.probabilityPercentage.setText(_translate("MainWindow", "percentage"))
        self.accessLabel.setText(_translate("MainWindow", "Access "))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))


import Icons_rc

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
